// Generated by view binder compiler. Do not edit!
package com.project.onestop.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.floatingactionbutton.FloatingActionButton;
import com.project.onestop.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityUserDashboardBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView ambulance;

  @NonNull
  public final LinearLayout ambulanceLocation;

  @NonNull
  public final FloatingActionButton chat;

  @NonNull
  public final ImageView emptyBox;

  @NonNull
  public final ImageView imageView2;

  @NonNull
  public final LinearLayout linearLayout;

  @NonNull
  public final LinearLayout linearLayout2;

  @NonNull
  public final TextView locationUser;

  @NonNull
  public final ConstraintLayout main;

  @NonNull
  public final LinearLayout profile;

  @NonNull
  public final ProgressBar progressBar;

  @NonNull
  public final ProgressBar progressBar3;

  @NonNull
  public final LinearLayout requestes;

  @NonNull
  public final RecyclerView rvzl;

  @NonNull
  public final TextView textView10;

  @NonNull
  public final TextView textView2;

  @NonNull
  public final TextView usetTxt;

  @NonNull
  public final View view2;

  @NonNull
  public final LinearLayout viewComplaints;

  private ActivityUserDashboardBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageView ambulance, @NonNull LinearLayout ambulanceLocation,
      @NonNull FloatingActionButton chat, @NonNull ImageView emptyBox,
      @NonNull ImageView imageView2, @NonNull LinearLayout linearLayout,
      @NonNull LinearLayout linearLayout2, @NonNull TextView locationUser,
      @NonNull ConstraintLayout main, @NonNull LinearLayout profile,
      @NonNull ProgressBar progressBar, @NonNull ProgressBar progressBar3,
      @NonNull LinearLayout requestes, @NonNull RecyclerView rvzl, @NonNull TextView textView10,
      @NonNull TextView textView2, @NonNull TextView usetTxt, @NonNull View view2,
      @NonNull LinearLayout viewComplaints) {
    this.rootView = rootView;
    this.ambulance = ambulance;
    this.ambulanceLocation = ambulanceLocation;
    this.chat = chat;
    this.emptyBox = emptyBox;
    this.imageView2 = imageView2;
    this.linearLayout = linearLayout;
    this.linearLayout2 = linearLayout2;
    this.locationUser = locationUser;
    this.main = main;
    this.profile = profile;
    this.progressBar = progressBar;
    this.progressBar3 = progressBar3;
    this.requestes = requestes;
    this.rvzl = rvzl;
    this.textView10 = textView10;
    this.textView2 = textView2;
    this.usetTxt = usetTxt;
    this.view2 = view2;
    this.viewComplaints = viewComplaints;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityUserDashboardBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityUserDashboardBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_user_dashboard, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityUserDashboardBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.ambulance;
      ImageView ambulance = ViewBindings.findChildViewById(rootView, id);
      if (ambulance == null) {
        break missingId;
      }

      id = R.id.ambulanceLocation;
      LinearLayout ambulanceLocation = ViewBindings.findChildViewById(rootView, id);
      if (ambulanceLocation == null) {
        break missingId;
      }

      id = R.id.chat;
      FloatingActionButton chat = ViewBindings.findChildViewById(rootView, id);
      if (chat == null) {
        break missingId;
      }

      id = R.id.emptyBox;
      ImageView emptyBox = ViewBindings.findChildViewById(rootView, id);
      if (emptyBox == null) {
        break missingId;
      }

      id = R.id.imageView2;
      ImageView imageView2 = ViewBindings.findChildViewById(rootView, id);
      if (imageView2 == null) {
        break missingId;
      }

      id = R.id.linearLayout;
      LinearLayout linearLayout = ViewBindings.findChildViewById(rootView, id);
      if (linearLayout == null) {
        break missingId;
      }

      id = R.id.linearLayout2;
      LinearLayout linearLayout2 = ViewBindings.findChildViewById(rootView, id);
      if (linearLayout2 == null) {
        break missingId;
      }

      id = R.id.location_User;
      TextView locationUser = ViewBindings.findChildViewById(rootView, id);
      if (locationUser == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      id = R.id.profile;
      LinearLayout profile = ViewBindings.findChildViewById(rootView, id);
      if (profile == null) {
        break missingId;
      }

      id = R.id.progressBar;
      ProgressBar progressBar = ViewBindings.findChildViewById(rootView, id);
      if (progressBar == null) {
        break missingId;
      }

      id = R.id.progressBar3;
      ProgressBar progressBar3 = ViewBindings.findChildViewById(rootView, id);
      if (progressBar3 == null) {
        break missingId;
      }

      id = R.id.requestes;
      LinearLayout requestes = ViewBindings.findChildViewById(rootView, id);
      if (requestes == null) {
        break missingId;
      }

      id = R.id.rvzl;
      RecyclerView rvzl = ViewBindings.findChildViewById(rootView, id);
      if (rvzl == null) {
        break missingId;
      }

      id = R.id.textView10;
      TextView textView10 = ViewBindings.findChildViewById(rootView, id);
      if (textView10 == null) {
        break missingId;
      }

      id = R.id.textView2;
      TextView textView2 = ViewBindings.findChildViewById(rootView, id);
      if (textView2 == null) {
        break missingId;
      }

      id = R.id.usetTxt;
      TextView usetTxt = ViewBindings.findChildViewById(rootView, id);
      if (usetTxt == null) {
        break missingId;
      }

      id = R.id.view2;
      View view2 = ViewBindings.findChildViewById(rootView, id);
      if (view2 == null) {
        break missingId;
      }

      id = R.id.viewComplaints;
      LinearLayout viewComplaints = ViewBindings.findChildViewById(rootView, id);
      if (viewComplaints == null) {
        break missingId;
      }

      return new ActivityUserDashboardBinding((ConstraintLayout) rootView, ambulance,
          ambulanceLocation, chat, emptyBox, imageView2, linearLayout, linearLayout2, locationUser,
          main, profile, progressBar, progressBar3, requestes, rvzl, textView10, textView2, usetTxt,
          view2, viewComplaints);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
