// Generated by view binder compiler. Do not edit!
package com.project.onestop.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.project.onestop.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityProfileBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final CardView cardView;

  @NonNull
  public final TextView editTextAdress;

  @NonNull
  public final TextView editTextEmail;

  @NonNull
  public final TextView editTextMoblie;

  @NonNull
  public final TextView editTextName;

  @NonNull
  public final TextView editTextPassword;

  @NonNull
  public final ScrollView main;

  @NonNull
  public final TextView textView;

  @NonNull
  public final Button userLogout;

  private ActivityProfileBinding(@NonNull ScrollView rootView, @NonNull CardView cardView,
      @NonNull TextView editTextAdress, @NonNull TextView editTextEmail,
      @NonNull TextView editTextMoblie, @NonNull TextView editTextName,
      @NonNull TextView editTextPassword, @NonNull ScrollView main, @NonNull TextView textView,
      @NonNull Button userLogout) {
    this.rootView = rootView;
    this.cardView = cardView;
    this.editTextAdress = editTextAdress;
    this.editTextEmail = editTextEmail;
    this.editTextMoblie = editTextMoblie;
    this.editTextName = editTextName;
    this.editTextPassword = editTextPassword;
    this.main = main;
    this.textView = textView;
    this.userLogout = userLogout;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityProfileBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityProfileBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_profile, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityProfileBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.cardView;
      CardView cardView = ViewBindings.findChildViewById(rootView, id);
      if (cardView == null) {
        break missingId;
      }

      id = R.id.editTextAdress;
      TextView editTextAdress = ViewBindings.findChildViewById(rootView, id);
      if (editTextAdress == null) {
        break missingId;
      }

      id = R.id.editTextEmail;
      TextView editTextEmail = ViewBindings.findChildViewById(rootView, id);
      if (editTextEmail == null) {
        break missingId;
      }

      id = R.id.editTextMoblie;
      TextView editTextMoblie = ViewBindings.findChildViewById(rootView, id);
      if (editTextMoblie == null) {
        break missingId;
      }

      id = R.id.editTextName;
      TextView editTextName = ViewBindings.findChildViewById(rootView, id);
      if (editTextName == null) {
        break missingId;
      }

      id = R.id.editTextPassword;
      TextView editTextPassword = ViewBindings.findChildViewById(rootView, id);
      if (editTextPassword == null) {
        break missingId;
      }

      ScrollView main = (ScrollView) rootView;

      id = R.id.textView;
      TextView textView = ViewBindings.findChildViewById(rootView, id);
      if (textView == null) {
        break missingId;
      }

      id = R.id.userLogout;
      Button userLogout = ViewBindings.findChildViewById(rootView, id);
      if (userLogout == null) {
        break missingId;
      }

      return new ActivityProfileBinding((ScrollView) rootView, cardView, editTextAdress,
          editTextEmail, editTextMoblie, editTextName, editTextPassword, main, textView,
          userLogout);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
