// Generated by view binder compiler. Do not edit!
package com.project.onestop.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.project.onestop.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityAdminDashboardBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final CardView addCabs;

  @NonNull
  public final CardView addEvnst;

  @NonNull
  public final TextView adminTxt;

  @NonNull
  public final ImageView imageView4;

  @NonNull
  public final LinearLayout linearLayoutCards;

  @NonNull
  public final Button logout;

  @NonNull
  public final ConstraintLayout main;

  @NonNull
  public final TextView textView4;

  @NonNull
  public final View view;

  @NonNull
  public final CardView viewCabs;

  @NonNull
  public final CardView viewEvents;

  private ActivityAdminDashboardBinding(@NonNull ConstraintLayout rootView,
      @NonNull CardView addCabs, @NonNull CardView addEvnst, @NonNull TextView adminTxt,
      @NonNull ImageView imageView4, @NonNull LinearLayout linearLayoutCards,
      @NonNull Button logout, @NonNull ConstraintLayout main, @NonNull TextView textView4,
      @NonNull View view, @NonNull CardView viewCabs, @NonNull CardView viewEvents) {
    this.rootView = rootView;
    this.addCabs = addCabs;
    this.addEvnst = addEvnst;
    this.adminTxt = adminTxt;
    this.imageView4 = imageView4;
    this.linearLayoutCards = linearLayoutCards;
    this.logout = logout;
    this.main = main;
    this.textView4 = textView4;
    this.view = view;
    this.viewCabs = viewCabs;
    this.viewEvents = viewEvents;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityAdminDashboardBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityAdminDashboardBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_admin_dashboard, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityAdminDashboardBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.addCabs;
      CardView addCabs = ViewBindings.findChildViewById(rootView, id);
      if (addCabs == null) {
        break missingId;
      }

      id = R.id.addEvnst;
      CardView addEvnst = ViewBindings.findChildViewById(rootView, id);
      if (addEvnst == null) {
        break missingId;
      }

      id = R.id.adminTxt;
      TextView adminTxt = ViewBindings.findChildViewById(rootView, id);
      if (adminTxt == null) {
        break missingId;
      }

      id = R.id.imageView4;
      ImageView imageView4 = ViewBindings.findChildViewById(rootView, id);
      if (imageView4 == null) {
        break missingId;
      }

      id = R.id.linearLayoutCards;
      LinearLayout linearLayoutCards = ViewBindings.findChildViewById(rootView, id);
      if (linearLayoutCards == null) {
        break missingId;
      }

      id = R.id.logout;
      Button logout = ViewBindings.findChildViewById(rootView, id);
      if (logout == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      id = R.id.textView4;
      TextView textView4 = ViewBindings.findChildViewById(rootView, id);
      if (textView4 == null) {
        break missingId;
      }

      id = R.id.view;
      View view = ViewBindings.findChildViewById(rootView, id);
      if (view == null) {
        break missingId;
      }

      id = R.id.viewCabs;
      CardView viewCabs = ViewBindings.findChildViewById(rootView, id);
      if (viewCabs == null) {
        break missingId;
      }

      id = R.id.viewEvents;
      CardView viewEvents = ViewBindings.findChildViewById(rootView, id);
      if (viewEvents == null) {
        break missingId;
      }

      return new ActivityAdminDashboardBinding((ConstraintLayout) rootView, addCabs, addEvnst,
          adminTxt, imageView4, linearLayoutCards, logout, main, textView4, view, viewCabs,
          viewEvents);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
