// Generated by view binder compiler. Do not edit!
package com.project.onestop.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.project.onestop.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityEventDashboardBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final CardView accepted;

  @NonNull
  public final CardView completed;

  @NonNull
  public final LinearLayout linearLayout2;

  @NonNull
  public final ConstraintLayout main;

  @NonNull
  public final CardView profile;

  @NonNull
  public final CardView requested;

  @NonNull
  public final TextView usetTxt;

  private ActivityEventDashboardBinding(@NonNull ConstraintLayout rootView,
      @NonNull CardView accepted, @NonNull CardView completed, @NonNull LinearLayout linearLayout2,
      @NonNull ConstraintLayout main, @NonNull CardView profile, @NonNull CardView requested,
      @NonNull TextView usetTxt) {
    this.rootView = rootView;
    this.accepted = accepted;
    this.completed = completed;
    this.linearLayout2 = linearLayout2;
    this.main = main;
    this.profile = profile;
    this.requested = requested;
    this.usetTxt = usetTxt;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityEventDashboardBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityEventDashboardBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_event_dashboard, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityEventDashboardBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.accepted;
      CardView accepted = ViewBindings.findChildViewById(rootView, id);
      if (accepted == null) {
        break missingId;
      }

      id = R.id.completed;
      CardView completed = ViewBindings.findChildViewById(rootView, id);
      if (completed == null) {
        break missingId;
      }

      id = R.id.linearLayout2;
      LinearLayout linearLayout2 = ViewBindings.findChildViewById(rootView, id);
      if (linearLayout2 == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      id = R.id.profile;
      CardView profile = ViewBindings.findChildViewById(rootView, id);
      if (profile == null) {
        break missingId;
      }

      id = R.id.requested;
      CardView requested = ViewBindings.findChildViewById(rootView, id);
      if (requested == null) {
        break missingId;
      }

      id = R.id.usetTxt;
      TextView usetTxt = ViewBindings.findChildViewById(rootView, id);
      if (usetTxt == null) {
        break missingId;
      }

      return new ActivityEventDashboardBinding((ConstraintLayout) rootView, accepted, completed,
          linearLayout2, main, profile, requested, usetTxt);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
