// Generated by view binder compiler. Do not edit!
package com.project.onestop.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.ProgressBar;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.AppCompatButton;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.project.onestop.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityRegisterBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final TextView Login;

  @NonNull
  public final AppCompatButton addData;

  @NonNull
  public final EditText editTextAdress;

  @NonNull
  public final EditText editTextEmail;

  @NonNull
  public final EditText editTextMoblie;

  @NonNull
  public final EditText editTextName;

  @NonNull
  public final EditText editTextPassword;

  @NonNull
  public final ScrollView main;

  @NonNull
  public final TextView newtextview;

  @NonNull
  public final ProgressBar progressBar5;

  private ActivityRegisterBinding(@NonNull ScrollView rootView, @NonNull TextView Login,
      @NonNull AppCompatButton addData, @NonNull EditText editTextAdress,
      @NonNull EditText editTextEmail, @NonNull EditText editTextMoblie,
      @NonNull EditText editTextName, @NonNull EditText editTextPassword, @NonNull ScrollView main,
      @NonNull TextView newtextview, @NonNull ProgressBar progressBar5) {
    this.rootView = rootView;
    this.Login = Login;
    this.addData = addData;
    this.editTextAdress = editTextAdress;
    this.editTextEmail = editTextEmail;
    this.editTextMoblie = editTextMoblie;
    this.editTextName = editTextName;
    this.editTextPassword = editTextPassword;
    this.main = main;
    this.newtextview = newtextview;
    this.progressBar5 = progressBar5;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityRegisterBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityRegisterBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_register, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityRegisterBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.Login;
      TextView Login = ViewBindings.findChildViewById(rootView, id);
      if (Login == null) {
        break missingId;
      }

      id = R.id.addData;
      AppCompatButton addData = ViewBindings.findChildViewById(rootView, id);
      if (addData == null) {
        break missingId;
      }

      id = R.id.editTextAdress;
      EditText editTextAdress = ViewBindings.findChildViewById(rootView, id);
      if (editTextAdress == null) {
        break missingId;
      }

      id = R.id.editTextEmail;
      EditText editTextEmail = ViewBindings.findChildViewById(rootView, id);
      if (editTextEmail == null) {
        break missingId;
      }

      id = R.id.editTextMoblie;
      EditText editTextMoblie = ViewBindings.findChildViewById(rootView, id);
      if (editTextMoblie == null) {
        break missingId;
      }

      id = R.id.editTextName;
      EditText editTextName = ViewBindings.findChildViewById(rootView, id);
      if (editTextName == null) {
        break missingId;
      }

      id = R.id.editTextPassword;
      EditText editTextPassword = ViewBindings.findChildViewById(rootView, id);
      if (editTextPassword == null) {
        break missingId;
      }

      ScrollView main = (ScrollView) rootView;

      id = R.id.newtextview;
      TextView newtextview = ViewBindings.findChildViewById(rootView, id);
      if (newtextview == null) {
        break missingId;
      }

      id = R.id.progressBar5;
      ProgressBar progressBar5 = ViewBindings.findChildViewById(rootView, id);
      if (progressBar5 == null) {
        break missingId;
      }

      return new ActivityRegisterBinding((ScrollView) rootView, Login, addData, editTextAdress,
          editTextEmail, editTextMoblie, editTextName, editTextPassword, main, newtextview,
          progressBar5);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
