// Generated by view binder compiler. Do not edit!
package com.project.onestop.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.RatingBar;
import android.widget.ScrollView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.AppCompatButton;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.textfield.TextInputEditText;
import com.project.onestop.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityAddNgoBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final AppCompatButton button1;

  @NonNull
  public final LinearLayout driverLayout;

  @NonNull
  public final ImageView image;

  @NonNull
  public final ProgressBar loadingBar;

  @NonNull
  public final TextInputEditText location;

  @NonNull
  public final ScrollView main;

  @NonNull
  public final TextInputEditText mobile;

  @NonNull
  public final RatingBar ratingBar;

  @NonNull
  public final TextInputEditText tiEmail;

  @NonNull
  public final TextInputEditText tiName;

  @NonNull
  public final TextInputEditText tiPassword;

  private ActivityAddNgoBinding(@NonNull ScrollView rootView, @NonNull AppCompatButton button1,
      @NonNull LinearLayout driverLayout, @NonNull ImageView image, @NonNull ProgressBar loadingBar,
      @NonNull TextInputEditText location, @NonNull ScrollView main,
      @NonNull TextInputEditText mobile, @NonNull RatingBar ratingBar,
      @NonNull TextInputEditText tiEmail, @NonNull TextInputEditText tiName,
      @NonNull TextInputEditText tiPassword) {
    this.rootView = rootView;
    this.button1 = button1;
    this.driverLayout = driverLayout;
    this.image = image;
    this.loadingBar = loadingBar;
    this.location = location;
    this.main = main;
    this.mobile = mobile;
    this.ratingBar = ratingBar;
    this.tiEmail = tiEmail;
    this.tiName = tiName;
    this.tiPassword = tiPassword;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityAddNgoBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityAddNgoBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_add_ngo, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityAddNgoBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.button1;
      AppCompatButton button1 = ViewBindings.findChildViewById(rootView, id);
      if (button1 == null) {
        break missingId;
      }

      id = R.id.driverLayout;
      LinearLayout driverLayout = ViewBindings.findChildViewById(rootView, id);
      if (driverLayout == null) {
        break missingId;
      }

      id = R.id.image;
      ImageView image = ViewBindings.findChildViewById(rootView, id);
      if (image == null) {
        break missingId;
      }

      id = R.id.loadingBar;
      ProgressBar loadingBar = ViewBindings.findChildViewById(rootView, id);
      if (loadingBar == null) {
        break missingId;
      }

      id = R.id.location;
      TextInputEditText location = ViewBindings.findChildViewById(rootView, id);
      if (location == null) {
        break missingId;
      }

      ScrollView main = (ScrollView) rootView;

      id = R.id.mobile;
      TextInputEditText mobile = ViewBindings.findChildViewById(rootView, id);
      if (mobile == null) {
        break missingId;
      }

      id = R.id.ratingBar;
      RatingBar ratingBar = ViewBindings.findChildViewById(rootView, id);
      if (ratingBar == null) {
        break missingId;
      }

      id = R.id.tiEmail;
      TextInputEditText tiEmail = ViewBindings.findChildViewById(rootView, id);
      if (tiEmail == null) {
        break missingId;
      }

      id = R.id.tiName;
      TextInputEditText tiName = ViewBindings.findChildViewById(rootView, id);
      if (tiName == null) {
        break missingId;
      }

      id = R.id.tiPassword;
      TextInputEditText tiPassword = ViewBindings.findChildViewById(rootView, id);
      if (tiPassword == null) {
        break missingId;
      }

      return new ActivityAddNgoBinding((ScrollView) rootView, button1, driverLayout, image,
          loadingBar, location, main, mobile, ratingBar, tiEmail, tiName, tiPassword);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
