// Generated by view binder compiler. Do not edit!
package com.project.onestop.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.AppCompatButton;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.project.onestop.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class OrderLayoutBinding implements ViewBinding {
  @NonNull
  private final CardView rootView;

  @NonNull
  public final AppCompatButton btnClickON;

  @NonNull
  public final TextView orderId;

  @NonNull
  public final TextView paymentInfo;

  @NonNull
  public final TextView time;

  private OrderLayoutBinding(@NonNull CardView rootView, @NonNull AppCompatButton btnClickON,
      @NonNull TextView orderId, @NonNull TextView paymentInfo, @NonNull TextView time) {
    this.rootView = rootView;
    this.btnClickON = btnClickON;
    this.orderId = orderId;
    this.paymentInfo = paymentInfo;
    this.time = time;
  }

  @Override
  @NonNull
  public CardView getRoot() {
    return rootView;
  }

  @NonNull
  public static OrderLayoutBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static OrderLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.order_layout, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static OrderLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btn_ClickON;
      AppCompatButton btnClickON = ViewBindings.findChildViewById(rootView, id);
      if (btnClickON == null) {
        break missingId;
      }

      id = R.id.orderId;
      TextView orderId = ViewBindings.findChildViewById(rootView, id);
      if (orderId == null) {
        break missingId;
      }

      id = R.id.paymentInfo;
      TextView paymentInfo = ViewBindings.findChildViewById(rootView, id);
      if (paymentInfo == null) {
        break missingId;
      }

      id = R.id.time;
      TextView time = ViewBindings.findChildViewById(rootView, id);
      if (time == null) {
        break missingId;
      }

      return new OrderLayoutBinding((CardView) rootView, btnClickON, orderId, paymentInfo, time);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
