// Generated by view binder compiler. Do not edit!
package com.project.onestop.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.project.onestop.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class RequestLayoutBinding implements ViewBinding {
  @NonNull
  private final CardView rootView;

  @NonNull
  public final Button btnSendRequest;

  @NonNull
  public final LinearLayout contentContainer;

  @NonNull
  public final ImageView ivCall;

  @NonNull
  public final ImageView ivProduct;

  @NonNull
  public final TextView tvPetAge;

  @NonNull
  public final TextView tvPetName;

  @NonNull
  public final TextView tvStatus;

  private RequestLayoutBinding(@NonNull CardView rootView, @NonNull Button btnSendRequest,
      @NonNull LinearLayout contentContainer, @NonNull ImageView ivCall,
      @NonNull ImageView ivProduct, @NonNull TextView tvPetAge, @NonNull TextView tvPetName,
      @NonNull TextView tvStatus) {
    this.rootView = rootView;
    this.btnSendRequest = btnSendRequest;
    this.contentContainer = contentContainer;
    this.ivCall = ivCall;
    this.ivProduct = ivProduct;
    this.tvPetAge = tvPetAge;
    this.tvPetName = tvPetName;
    this.tvStatus = tvStatus;
  }

  @Override
  @NonNull
  public CardView getRoot() {
    return rootView;
  }

  @NonNull
  public static RequestLayoutBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static RequestLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.request_layout, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static RequestLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnSendRequest;
      Button btnSendRequest = ViewBindings.findChildViewById(rootView, id);
      if (btnSendRequest == null) {
        break missingId;
      }

      id = R.id.contentContainer;
      LinearLayout contentContainer = ViewBindings.findChildViewById(rootView, id);
      if (contentContainer == null) {
        break missingId;
      }

      id = R.id.ivCall;
      ImageView ivCall = ViewBindings.findChildViewById(rootView, id);
      if (ivCall == null) {
        break missingId;
      }

      id = R.id.ivProduct;
      ImageView ivProduct = ViewBindings.findChildViewById(rootView, id);
      if (ivProduct == null) {
        break missingId;
      }

      id = R.id.tvPetAge;
      TextView tvPetAge = ViewBindings.findChildViewById(rootView, id);
      if (tvPetAge == null) {
        break missingId;
      }

      id = R.id.tvPetName;
      TextView tvPetName = ViewBindings.findChildViewById(rootView, id);
      if (tvPetName == null) {
        break missingId;
      }

      id = R.id.tvStatus;
      TextView tvStatus = ViewBindings.findChildViewById(rootView, id);
      if (tvStatus == null) {
        break missingId;
      }

      return new RequestLayoutBinding((CardView) rootView, btnSendRequest, contentContainer, ivCall,
          ivProduct, tvPetAge, tvPetName, tvStatus);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
