// Generated by view binder compiler. Do not edit!
package com.project.onestop.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.RatingBar;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.project.onestop.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ViewNgoBinding implements ViewBinding {
  @NonNull
  private final CardView rootView;

  @NonNull
  public final CardView cardviewappoint;

  @NonNull
  public final LinearLayout linearLayout;

  @NonNull
  public final RatingBar ratingBar;

  @NonNull
  public final TextView sellerLocation;

  @NonNull
  public final TextView sellerName;

  @NonNull
  public final TextView sellerRating;

  @NonNull
  public final View viewDivider;

  private ViewNgoBinding(@NonNull CardView rootView, @NonNull CardView cardviewappoint,
      @NonNull LinearLayout linearLayout, @NonNull RatingBar ratingBar,
      @NonNull TextView sellerLocation, @NonNull TextView sellerName,
      @NonNull TextView sellerRating, @NonNull View viewDivider) {
    this.rootView = rootView;
    this.cardviewappoint = cardviewappoint;
    this.linearLayout = linearLayout;
    this.ratingBar = ratingBar;
    this.sellerLocation = sellerLocation;
    this.sellerName = sellerName;
    this.sellerRating = sellerRating;
    this.viewDivider = viewDivider;
  }

  @Override
  @NonNull
  public CardView getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewNgoBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ViewNgoBinding inflate(@NonNull LayoutInflater inflater, @Nullable ViewGroup parent,
      boolean attachToParent) {
    View root = inflater.inflate(R.layout.view_ngo, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ViewNgoBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      CardView cardviewappoint = (CardView) rootView;

      id = R.id.linearLayout;
      LinearLayout linearLayout = ViewBindings.findChildViewById(rootView, id);
      if (linearLayout == null) {
        break missingId;
      }

      id = R.id.ratingBar;
      RatingBar ratingBar = ViewBindings.findChildViewById(rootView, id);
      if (ratingBar == null) {
        break missingId;
      }

      id = R.id.sellerLocation;
      TextView sellerLocation = ViewBindings.findChildViewById(rootView, id);
      if (sellerLocation == null) {
        break missingId;
      }

      id = R.id.sellerName;
      TextView sellerName = ViewBindings.findChildViewById(rootView, id);
      if (sellerName == null) {
        break missingId;
      }

      id = R.id.sellerRating;
      TextView sellerRating = ViewBindings.findChildViewById(rootView, id);
      if (sellerRating == null) {
        break missingId;
      }

      id = R.id.viewDivider;
      View viewDivider = ViewBindings.findChildViewById(rootView, id);
      if (viewDivider == null) {
        break missingId;
      }

      return new ViewNgoBinding((CardView) rootView, cardviewappoint, linearLayout, ratingBar,
          sellerLocation, sellerName, sellerRating, viewDivider);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
