// Generated by view binder compiler. Do not edit!
package com.project.onestop.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.AppCompatButton;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.project.onestop.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ViewBoardlayoutBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView call;

  @NonNull
  public final TextView etName;

  @NonNull
  public final LinearLayout image;

  @NonNull
  public final ImageView ivProduct;

  @NonNull
  public final AppCompatButton sendRequest;

  @NonNull
  public final TextView status;

  private ViewBoardlayoutBinding(@NonNull ConstraintLayout rootView, @NonNull ImageView call,
      @NonNull TextView etName, @NonNull LinearLayout image, @NonNull ImageView ivProduct,
      @NonNull AppCompatButton sendRequest, @NonNull TextView status) {
    this.rootView = rootView;
    this.call = call;
    this.etName = etName;
    this.image = image;
    this.ivProduct = ivProduct;
    this.sendRequest = sendRequest;
    this.status = status;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewBoardlayoutBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ViewBoardlayoutBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.view_boardlayout, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ViewBoardlayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.call;
      ImageView call = ViewBindings.findChildViewById(rootView, id);
      if (call == null) {
        break missingId;
      }

      id = R.id.etName;
      TextView etName = ViewBindings.findChildViewById(rootView, id);
      if (etName == null) {
        break missingId;
      }

      id = R.id.image;
      LinearLayout image = ViewBindings.findChildViewById(rootView, id);
      if (image == null) {
        break missingId;
      }

      id = R.id.ivProduct;
      ImageView ivProduct = ViewBindings.findChildViewById(rootView, id);
      if (ivProduct == null) {
        break missingId;
      }

      id = R.id.sendRequest;
      AppCompatButton sendRequest = ViewBindings.findChildViewById(rootView, id);
      if (sendRequest == null) {
        break missingId;
      }

      id = R.id.status;
      TextView status = ViewBindings.findChildViewById(rootView, id);
      if (status == null) {
        break missingId;
      }

      return new ViewBoardlayoutBinding((ConstraintLayout) rootView, call, etName, image, ivProduct,
          sendRequest, status);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
